# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
